[package]
name = "step_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.20.1"
winit = "0.29.15"
pollster = "0.3.0"
bytemuck = "1.16.1"